config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  company     :string
#  description :text
#  title       :string
#  url         :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint
#
# Indexes
#
#  index_tasks_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#
class Task < ApplicationRecord
  belongs_to :category

  scope :list_by_category, ->(category) { where(category_id: category) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def self.categories_all
    @categories = Category.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[edit show update destroy]
  def index
    return @tasks = Task.all.order(created_at: :desc) unless params[:category].present?

    category = Category.find_by(name: params[:category])
    @tasks = Task.list_by_category(category.id)
  end

  def new
    @task = Task.new
  end

  def edit; end

  def show; end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :company, :url, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rabbit</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if notice.present? || alert.present? %>
  <div aria-live="polite" aria-atomic="true" class="position-relative">
    <div class="toast-container top-0 end-0 p-3">
      <% flash.each do |type, msg| %>
        <div class="toast bg-primary" role='alert' aria-atomic="true" aria-live="assertive">
          <div class="d-flex">
            <div class="toast-body">
              <div>
                <%= msg %>
              </div>
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="#">TaskRabbit</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to 'All Tasks', root_path, class: 'nav-link' %></li>
        <% ApplicationController.categories_all.each do |category| %>
          <li class="nav-item"><%= link_to category.name, tasks_path(category: category.name), class: 'nav-link' %></li>
        <% end %>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to 'New Task', new_task_path, class: 'nav-link' %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
 <div class="offset-md-2 col-md-8">
   <%= yield %>
 </div>
</div>

</body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task, html: { class: 'form-horizontal' } do |f| %>
  <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: 'choose a category' }, class: 'form-select mb-3' %>
  <%= f.input :title, label: 'task title' %>
  <%= f.input :description, label: 'task description' %>
  <%= f.input :company, label: 'your company' %>
  <%= f.input :url, label: 'link to task' %>
  <br>
  <%= f.button :submit, class: 'btn btn-white' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/tasks/index.html.erb
<div id="jobs">
  <% @tasks.each do |task| %>
    <div class="job">
      <h2><%= link_to task.title, task_path(task) %></h2>
      <p><%= task.company %></p>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/tasks/show.html.erb
<div id="jobs">
  <div class="job">
    <h1><%= @task.title %></h1>
    <p><%= @task.description %></p>
    <p><%= @task.company %></p>
    <button class="btn btn-white"><%= link_to 'complete task', @task.url, class: 'text-decoration-none' %></button>
  </div>
</div>

<div id="links">
  <%= link_to 'Home', root_path, class: 'btn btn-white btn-sm' %>
  <%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-white btn-sm' %>
  <%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: 'are you sure?' }, class: 'btn btn-white btn-sm' %>
</div>